### ISSUE TITLE
Garbage collection?

### ISSUE THREAD

**Issue by mfbx9da4** [leafac/sqlite#1]
This is probably nitpicking but by never purging statements couldn't this cause a memory leak?

https://github.com/leafac/sqlite/blob/master/src/index.ts#L98

Theoretically, for a long running application, the statements will never be cleaned up.

I'll admit this is quite edge case as it's unlikely an application would dynamically generate SQL statements on the flie or have so many unique queries. Nevertheless, I suppose it would be easy enough to add a line like 

```ts
if (this.statements.size === MAX_SIZE) {
  this.statements.delete(this.statements.keys().next().value))
}
```

**Comment by leafac** [comment]
Thanks for looking at my library and for reaching out 😀

You’re right, and this is by design: I opted to not implemented any cache eviction policy because in most applications you’re running the same queries over and over, not creating arbitrarily many new queries. You’re always welcome to access `database.statements` and implement whatever cache eviction policy is reasonable for your application. For example, you’d get to pick the `MAX_SIZE`, which I guess is the hard to part (What would be an appropriate `MAX_SIZE` for every application? What if my application has exactly `MAX_SIZE + 1` queries, and they’re run in a round-robin manner (then everything is a cache miss)? And so forth…).

More information: https://github.com/leafac/sqlite#how-it-works & https://youtu.be/ORdYNOwpcsY

**Comment by mfbx9da4** [comment]
Yeah great points!
